### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by gau-nernst** [gau-nernst/centernet-lightning#1]
- [ ] Remove ImageNet normalization dependence
- [ ] Make it an installable package
- [ ] Provide some pre-trained weights
- [ ] Add demo photos / videos
- [ ] Add Colab notebook examples
- [ ] Better test coverage + Github CI
- [ ] Figure out package dependencies, minimum dependencies
